# Generated by Django 5.1.5 on 2025-06-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('title', models.CharField(default='Name', max_length=50, verbose_name='Name')),
                ('anons', models.CharField(default='Anons', max_length=250, verbose_name='Anons')),
                ('fill_text', models.TextField(verbose_name='Game_FILL')),
                ('url', models.URLField(blank=True, max_length=100, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
    ]
