# Generated by Django 5.1.5 on 2025-06-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finder',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
