# Generated by Django 5.1.4 on 2025-02-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Name', max_length=50, verbose_name='Name')),
                ('anons', models.CharField(default='Anons', max_length=250, verbose_name='Anons')),
                ('fill_text', models.TextField(verbose_name='News')),
                ('date', models.DateTimeField(verbose_name='Date publication')),
            ],
        ),
    ]
